"use client"
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/navbar/Navbar";
import Footer from "@/components/layout/footer/Footer";
import { Toaster } from 'react-hot-toast';
import {QueryClient ,QueryClientProvider} from "@tanstack/react-query"
import { FooterVisibilityProvider } from '@/components/context/FooterVisibilityContext';
const inter = Inter({ subsets: ["latin"] });

 const metadata: Metadata = {
  title: "Urstyle",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
 }: Readonly<{
  children: React.ReactNode;
 }>) {
  const queryClient = new QueryClient()
  return (
     <html>
       <head>
         {/* Include any head elements here, such as <title> or <meta> tags */}
       </head>
       
       <body>
       <FooterVisibilityProvider>
       {/* <QueryClientProvider client={queryClient}> */}
         <div className={inter.className}>{children}</div>
        <Footer />
        <Toaster /> 
      
        {/* </QueryClientProvider> */}
        </FooterVisibilityProvider>
       </body>
     </html>
  );
 }
 
 



// import Navbar from "@/components/layout/navbar/Navbar";
// import Footer from "@/components/layout/footer/Footer";
 
// export default function Layout({ children }: { children: React.ReactNode }) {
  
//     return (
//      <html>
//         <body>
//           <Navbar/>
//           {children}
//           <Footer/>
//        </body>
//      </html>
//    )
//   }
  
